### ISSUE TITLE
UserDefaults Improvement

### ISSUE THREAD

**Issue by chrisdhaan** [bblia/tipsy#2]
Currently you save `timeAppClosed`, `percentageLastClosed`, and `billLastClosed` in `viewWillDisappear`. This is a UIViewController lifecycle method and not an app lifecycle method. So it doesn't guarantee those values get saved on app close. It just guarantees they are saved when the SettingsViewController appears. I would try and save those variables to UserDefaults differently. Try saving `timeAppClosed` in AppDelegate (I'll let you figure out which method). Try saving `percentageLastClosed` in the `calculateTip` method. You could also try saving `billLastClosed` in the `calculateTip` method but I challenge you to try saving it using `UITextFieldDelegate`. Let me know if you need help!

**Comment by bblia** [comment]
eff u

**Comment by bblia** [comment]
hehe jk thank you for taking the time to see where i can learn more :)

**Comment by chrisdhaan** [comment]
Since you seem to not want to put any code ever at all besides Fabric initialization in `AppDelegate` you could also use `NotificationCenter` to save `timeAppClosed` in `TipViewController`. Challenge accepted? Though I would still learn the `AppDelegate` way even if you chose to use `NotificationCenter`.
